### ISSUE TITLE
Add Jenkins test job

### ISSUE THREAD

**Issue by adrianmoisey** [yola/drf-madprops#12]
Our current test script doesn't work with drf-madprops. The Jenkins job uses the name of the Jenkins job for the Github repo URL and the tests. Since `drf-madprops` provides `madprops` this breaks.

We could try fix this by using tox: https://github.com/yola/production/issues/2267

**Comment by thomasw** [comment]
This is a public repo. I thought our strategy was to use travis-ci for public repos.

**Comment by adrianmoisey** [comment]
I didn't realise we had a specific strategy.
This issue can stay around until we get some sort of automated testing.

**Comment by zoidbergwill** [comment]
When we add Travis, it'd be rad if we ran tests against different Django and DRF versions.

[Raven](https://github.com/getsentry/raven-python/blob/master/.travis.yml) is a known example of multiple Django versions.
